---
python: python3
git:
  salt:
    depth: 1
    branch: 2018.3
    origin: git@github.com:dwoz/salt.git
    remotes:
      saltstack: git@github.com:saltstack/salt.git
    config:
      user.email: dwozniak@saltstack.com
      user.name: Daniel A. Wozniak
      gpg.program: gpg
      commit.signgpg: true
  saltwinshell:
    depth: 1
    origin: git@github.com:dwoz/saltwinshell.git
    config:
      user.email: dwozniak@saltstack.com
      user.name: Daniel A. Wozniak
      gpg.program: gpg
      commit.signgpg: true
  srv/salt:
    depth: 1
    branch: 2018.3
    origin: git@github.com:dwoz/salt-jenkins.git
    remotes:
      saltstack: git@github.com:saltstack/salt-jenkins.git
    config:
      user.email: dwozniak@saltstack.com
      user.name: Daniel A. Wozniak
      gpg.program: gpg
      commit.signgpg: true
files:
  Saltfile:
    salt-run:
      config_dir: etc/salt
    salt:
      config_dir: etc/salt
    salt-call:
      config_dir: etc/salt
    salt-cloud:
      config_dir: etc/salt
    salt-master:
      config_dir: etc/salt
      log_file: var/log/salt-master.log
    salt-minion:
      config_dir: etc/salt
      log_file: var/log/salt-minion.log
    salt-ssh:
      config_dir: etc/salt
      ssh_log_file: var/log/salt.log
    salt-key:
      config_dir: etc/salt
  etc/salt/minion:
    id: minion
    master: localhost
    root_dir: ./
    log_file: var/salt/minion.log
  etc/salt/master:
    master_id: master
    root_dir: ./
    log_file: var/log/salt-master.log
    pillar_roots:
      base:
        - srv/pillar
    gpg_keydir: etc/salt/keys
    ssh_minion_opts:
      ec2_tags:
        keyid: ''
        key: ''
    ssh_log_file: var/salt.log
    # requires full path?
    file_roots:
      base:
        - srv/salt
  etc/salt/roster:
    test:
      host: 10.10.2.63
      user: Administrator
      passwd: ''
      winrm: True
  # Extra kitchen platform config.
  platforms.yml:
    platforms:
    - name: opensuse
      driver:
        instance_type: t2.large
        # spot_price: '0.04'
        image_search:
          owner-id: '679593333241'
          name: openSUSE-Leap-*-*-hvm-ssd-x86_64-*-ami-*
        tags:
          Name: kitchen-opensuse-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
      transport:
        username: ec2-user
      provisioner:
        salt_bootstrap_options: -UX -p rsync git v<%= version %>
        salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
    - name: centos-7
      driver:
        tags:
          Name: kitchen-centos-7-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
    - name: centos-6
      driver:
        tags:
          Name: kitchen-centos-6-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
      provisioner:
        salt_bootstrap_options: -P -p rsync -y -x python2.7 -X git v<%= version %> >/dev/null
    - name: fedora-26
      driver:
        tags:
          Name: kitchen-fedora-26-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
      provisioner:
        salt_bootstrap_options: -X -p rsync git v<%= version %> >/dev/null
    - name: fedora-27
      driver:
        tags:
          Name: kitchen-fedora-27-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
      provisioner:
        salt_bootstrap_options: -X -p rsync git v<%= version %>
    - name: ubuntu-17.10
      driver:
        tags:
          Name: kitchen-ubuntu-1710-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
    - name: ubuntu-16.04
      driver:
        tags:
          Name: kitchen-ubuntu-1604-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
    - name: ubuntu-14.04
      driver:
        tags:
          Name: kitchen-ubuntu-1404-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
    - name: debian-8
      driver:
        tags:
          Name: kitchen-debian-8-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
        block_device_mappings: null
    - name: debian-9
      driver:
        tags:
          Name: kitchen-debian-9-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
        block_device_mappings: null
    - name: arch
      driver:
        image_search:
          owner-id: '093273469852'
          name: arch-linux-hvm-*.x86_64-ebs
        tags:
          Name: kitchen-arch-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
      transport:
        username: root
      provisioner:
        salt_bootstrap_options: -X -p rsync git v<%= version %> >/dev/null
    - name: windows-2016
      driver:
        # spot_price: '0.04'
        instance_type: t2.xlarge
        tags:
          Name: kitchen-windows-2016-<%= 10.times.map{[('a'..'z').to_a, (0..9).to_a].join[rand(36)]}.join %>
        retryable_tries: 120
      provisioner:
        cache_commands:
          - find %{sandbox_path}/testing/tests -type f | xargs unix2dos
        salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1
        salt_bootstrap_options: -version <%= version %> -runservice false
        init_environment: |
          REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v PagingFiles /t REG_MULTI_SZ /d "D:\pagefile.sys 4096 8192" /f
          winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="5000"}'
      transport:
        name: winrm
      verifier:
        windows: true
        verbose: true
        coverage_xml: "%TEMP%\\coverage.xml"
        xml: "%TEMP%\\xml-unittests-output\\"
        save:
          $env:TEMP/coverage.xml: artifacts/coverage/coverage.xml
          $env:TEMP/xml-unittests-output/: artifacts/
          $env:TEMP/salt-runtests.log: artifacts/logs/salt-runtests.log
          c:/salt/var/log/salt/minion: artifacts/logs/minion
  # Extra kitchen platform config.
  driver.yml:
    driver:
      name: ec2
      associate_public_ip: false
      aws_ssh_key_id: dwoz
      block_device_mappings:
      - device_name: /dev/sda1
        ebs:
          delete_on_termination: true
          volume_size: 30
          volume_type: gp2
      # instance_type: t2.medium
      interface: public  # This can be set to "private" if you have everything setup to access it.
      associate_public_ip: true
      region: us-west-2
      require_chef_omnibus: true
      security_group_ids:
      # - sg-4d816135
      - sg-0c869eb4bf694353c
      # pot_price: 'nill'
      # subnet_id: subnet-01934e812f7300a97
      subnet_id: subnet-0255fcff51ec5b3c6
      tags:
        created-by: test-kitchen
    transport:
      name: rsync
      ssh_key: ~/.ssh/dwoz.pem
      timeout: 30

commands:
  - venv/bin/pip install tornado==4.5.3
  - venv/bin/pip install pyzmq==16.0.4
  - venv/bin/pip install -e salt
  - venv/bin/pip install cython
  - venv/bin/pip install -e saltwinshell
